import pandas as pd
import streamlit as st

from src.ui.charts import (
    build_allocation_dumbbell_chart,
    build_efficient_frontier_chart,
    build_horizontal_allocation_chart,
)

from src.ui.tables import (
    render_financial_table,
)

def format_percentage(value):
    """
    Formats a decimal value as a percentage.
    """

    if value is None or pd.isna(value):
        return "—"

    return f"{value * 100:.2f}%"


def format_ratio(value):
    """
    Formats a numeric ratio.
    """

    if value is None or pd.isna(value):
        return "—"

    return f"{value:.2f}"


def render_optimization_metric(
    label,
    value,
    detail,
    tone="neutral",
):
    """
    Builds one optimization metric.
    """

    return f"""
    <div class="rg-optimization-metric">
        <span class="rg-optimization-metric-label">
            {label}
        </span>

        <strong class="rg-optimization-metric-value {tone}">
            {value}
        </strong>

        <span class="rg-optimization-metric-detail">
            {detail}
        </span>
    </div>
    """


def render_chart_heading(
    eyebrow,
    title,
    description,
):
    """
    Renders a consistent section heading.
    """

    st.html(
        f"""
        <div class="rg-chart-heading">
            <div>
                <span>{eyebrow}</span>
                <h3>{title}</h3>
            </div>

            <p>{description}</p>
        </div>
        """
    )


def build_optimization_reading(
    current_sharpe,
    maximum_sharpe,
    current_volatility,
    minimum_volatility,
):
    """
    Creates a concise interpretation of the
    optimization results.
    """

    sharpe_difference = maximum_sharpe - current_sharpe

    volatility_difference = (
        current_volatility - minimum_volatility
    )

    if sharpe_difference > 0.10:
        sharpe_text = (
            "The simulated maximum-Sharpe allocation provides "
            "meaningfully stronger historical risk-adjusted returns "
            "than the current portfolio."
        )

    elif sharpe_difference > 0:
        sharpe_text = (
            "The maximum-Sharpe allocation offers a modest historical "
            "improvement in risk-adjusted performance."
        )

    else:
        sharpe_text = (
            "The current portfolio already compares favourably with "
            "the maximum-Sharpe portfolios generated by the model."
        )

    if volatility_difference > 0.02:
        volatility_text = (
            "The minimum-volatility allocation could materially "
            "reduce annualized portfolio volatility."
        )

    elif volatility_difference > 0:
        volatility_text = (
            "The minimum-volatility allocation offers a limited "
            "reduction in historical risk."
        )

    else:
        volatility_text = (
            "The current portfolio is already close to, or below, "
            "the minimum volatility identified by the simulation."
        )

    return f"{sharpe_text} {volatility_text}"


def render_optimization(
    results,
    risk_parity_df,
    current_weights,
):
    """
    Renders portfolio optimization, Risk Parity,
    allocation comparisons, and Efficient Frontier.
    """

    optimal_portfolios = (
        results["optimal_portfolios"].copy()
    )

    efficient_frontier = (
        results["efficient_frontier"].copy()
    )

    performance = results["performance_summary"]

    maximum_sharpe_name = "Maximum Sharpe Portfolio"
    minimum_volatility_name = "Minimum Volatility Portfolio"

    if maximum_sharpe_name in optimal_portfolios.index:
        maximum_sharpe_portfolio = (
            optimal_portfolios.loc[maximum_sharpe_name]
        )
    else:
        maximum_sharpe_portfolio = (
            optimal_portfolios.iloc[0]
        )

    if minimum_volatility_name in optimal_portfolios.index:
        minimum_volatility_portfolio = (
            optimal_portfolios.loc[minimum_volatility_name]
        )
    else:
        minimum_volatility_portfolio = (
            optimal_portfolios.iloc[-1]
        )

    maximum_sharpe_ratio = maximum_sharpe_portfolio[
        "Sharpe Ratio"
    ]

    maximum_sharpe_return = maximum_sharpe_portfolio[
        "Annualized Return"
    ]

    minimum_volatility = minimum_volatility_portfolio[
        "Annualized Volatility"
    ]

    minimum_volatility_return = minimum_volatility_portfolio[
        "Annualized Return"
    ]

    current_sharpe = performance["Sharpe Ratio"]
    current_volatility = performance[
        "Annualized Volatility"
    ]

    risk_parity_weights = (
        risk_parity_df["Weight"]
        .astype(float)
    )

    largest_risk_parity_asset = (
        risk_parity_weights.idxmax()
    )

    largest_risk_parity_weight = (
        risk_parity_weights.max()
    )

    metric_strip = "".join(
        [
            render_optimization_metric(
                label="Maximum Sharpe",
                value=format_ratio(
                    maximum_sharpe_ratio
                ),
                detail="Highest simulated Sharpe ratio",
                tone="positive",
            ),
            render_optimization_metric(
                label="Return at max Sharpe",
                value=format_percentage(
                    maximum_sharpe_return
                ),
                detail="Expected annualized return",
                tone=(
                    "positive"
                    if maximum_sharpe_return >= 0
                    else "negative"
                ),
            ),
            render_optimization_metric(
                label="Minimum volatility",
                value=format_percentage(
                    minimum_volatility
                ),
                detail="Lowest simulated annualized risk",
            ),
            render_optimization_metric(
                label="Largest risk-parity weight",
                value=format_percentage(
                    largest_risk_parity_weight
                ),
                detail=largest_risk_parity_asset,
            ),
        ]
    )

    optimization_reading = build_optimization_reading(
        current_sharpe=current_sharpe,
        maximum_sharpe=maximum_sharpe_ratio,
        current_volatility=current_volatility,
        minimum_volatility=minimum_volatility,
    )

    st.html(
        f"""
        <section class="rg-optimization">

            <div class="rg-section-heading">
                <div>
                    <span>PORTFOLIO CONSTRUCTION</span>
                    <h2>Allocation and optimization</h2>
                </div>

                <p>
                    Compare the current allocation with optimized
                    portfolios and alternative risk distributions.
                </p>
            </div>

            <div class="rg-optimization-strip">
                {metric_strip}
            </div>

            <div class="rg-optimization-reading">
                <span>ALLOCATION READING</span>

                <p>
                    {optimization_reading}
                </p>
            </div>

        </section>
        """
    )

    # =========================
    # OPTIMAL PORTFOLIOS
    # =========================

    render_chart_heading(
        eyebrow="OPTIMAL PORTFOLIOS",
        title="Maximum Sharpe and minimum volatility",
        description=(
            "Two reference portfolios selected from the "
            "complete set of simulated allocations."
        ),
    )

    weight_columns = [
        column
        for column in optimal_portfolios.columns
        if column.startswith("Weight ")
    ]

    render_financial_table(
        optimal_portfolios,
        index_label="Portfolio",
        percent_columns=[
            "Annualized Return",
            "Annualized Volatility",
            *weight_columns,
        ],
        ratio_columns=[
            "Sharpe Ratio",
        ],
        key="optimal_portfolios_table",
    )

    # =========================
    # CURRENT VS RISK PARITY
    # =========================

    render_chart_heading(
        eyebrow="ALLOCATION COMPARISON",
        title="Current portfolio vs Risk Parity",
        description=(
            "Risk Parity redistributes capital with the goal "
            "of balancing each asset's contribution to risk."
        ),
    )

    current_weights_series = pd.Series(
        current_weights,
        dtype=float,
        name="Current Portfolio",
    )

    current_weights_series = (
        current_weights_series
        .reindex(risk_parity_weights.index)
        .fillna(0.0)
    )

    weights_comparison = pd.DataFrame(
        {
            "Current Portfolio": (
                current_weights_series * 100
            ),
            "Risk Parity": (
                risk_parity_weights * 100
            ),
        }
    )

    weights_comparison.index.name = "Ticker"

    allocation_comparison_chart = (
        build_allocation_dumbbell_chart(
            weights_comparison
        )
    )

    st.altair_chart(
        allocation_comparison_chart,
        width="stretch",
        theme=None,
    )

    weights_comparison_table = (
        weights_comparison.rename(
            columns={
                "Current Portfolio": (
                    "Current Portfolio (%)"
                ),
                "Risk Parity": (
                    "Risk Parity (%)"
                ),
            }
        )
    )

    render_financial_table(
        weights_comparison_table,
        index_label="Ticker",
        percentage_point_columns=[
            "Current Portfolio (%)",
            "Risk Parity (%)",
        ],
        key="allocation_comparison_table",
    )

    # =========================
    # ORIGINAL RISK PARITY DATA
    # =========================

    render_chart_heading(
        eyebrow="RISK ALLOCATION",
        title="Risk Parity weights",
        description=(
            "Long-only allocation calculated by equalizing "
            "percentage risk contributions."
        ),
    )

    risk_parity_table = (
        risk_parity_df[
            ["Weight (%)"]
        ]
        .copy()
    )

    render_financial_table(
        risk_parity_table,
        index_label="Ticker",
        percentage_point_columns=[
            "Weight (%)",
        ],
        key="risk_parity_weights_table",
    )

    risk_parity_chart = (
        build_horizontal_allocation_chart(
            allocation_data=(
                risk_parity_df[["Weight (%)"]]
            ),
            value_column="Weight (%)",
        )
    )

    st.altair_chart(
        risk_parity_chart,
        width="stretch",
        theme=None,
    )

    # =========================
    # EFFICIENT FRONTIER
    # =========================

    render_chart_heading(
        eyebrow="RISK–RETURN SPACE",
        title="Efficient Frontier",
        description=(
            "Each point represents one simulated allocation "
            "with a different expected return and volatility."
        ),
    )

    efficient_frontier_chart = (
        build_efficient_frontier_chart(
            efficient_frontier=efficient_frontier,
            optimal_portfolios=optimal_portfolios,
        )
    )

    st.altair_chart(
        efficient_frontier_chart,
        width="stretch",
        theme=None,
    )

    with st.expander(
        "View Efficient Frontier data"
    ):
        frontier_weight_columns = [
            column
            for column in efficient_frontier.columns
            if column.startswith("Weight ")
        ]

        render_financial_table(
            efficient_frontier.head(100),
            percent_columns=[
                "Annualized Return",
                "Annualized Volatility",
                *frontier_weight_columns,
            ],
            ratio_columns=[
                "Sharpe Ratio",
            ],
            hide_index=True,
            height=430,
            key="efficient_frontier_table",
        )

        st.caption(
            "The table displays the first 100 simulated portfolios. "
            "Optimization and portfolio selection use the complete dataset."
        )

    with st.expander(
        "How to interpret portfolio optimization"
    ):
        st.write(
            """
            The Maximum Sharpe portfolio identifies the simulated
            allocation with the highest historical excess return
            per unit of volatility.

            The Minimum Volatility portfolio identifies the simulated
            allocation with the lowest annualized volatility.

            Risk Parity follows a different objective. Rather than
            maximizing return or minimizing volatility directly, it
            attempts to distribute portfolio risk more evenly across
            the selected assets.

            These results are based on historical estimates and should
            be treated as analytical references rather than guaranteed
            future outcomes.
            """
        )